export const FETCH_PATIENT_DATA = 'FETCH_PATIENT_DATA';
export const FETCH_PATIENT_DATA_SUCCESS = 'FETCH_PATIENT_DATA_SUCCESS';
export const FETCH_PATIENT_DATA_FAILURE = 'FETCH_PATIENT_DATA_FAILURE';

export const FETCH_DIARY_DATA = 'FETCH_DIARY_DATA';
export const FETCH_DIARY_DATA_SUCCESS = 'FETCH_DIARY_DATA_SUCCESS';
export const FETCH_DIARY_DATA_FAILURE = 'FETCH_DIARY_DATA_FAILURE';
